prepare:
  split: 0.20
  seed: 20170428

featurize:
  max_features: 3000
  ngrams: 2

train:
  seed: 20170428
  n_est: 100
  min_split: 64

outlier: 1
nested1:
  doubled: "first instance!"
  value: "Another one!"
  nested2:
    other: "share params?"
    nested3:
      value: "Another one!"
      nested4:
        value: "Another one!"
        nested5:
          nested6:
            nested7: "Lucky!"
        nested5b:
            nested6: "Wow!!!!!!!!!!!!!!!!!!!!"
            doubled: "second instance!"
