name: CML Report
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.sha || github.sha }}
  cancel-in-progress: true
jobs:
  run:
    continue-on-error: ${{ github.ref_name != 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Generate metrics report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml ci
          if test $GITHUB_REF_NAME == main; then
            PREVIOUS_REF=HEAD~1
          else
            PREVIOUS_REF=main
            git fetch --depth=1 origin $PREVIOUS_REF:$PREVIOUS_REF
          fi

          dvc plots diff $PREVIOUS_REF workspace \
            --show-vega --targets evaluation/plots/precision_recall.json > vega.json
          vl2svg vega.json prc.svg

          dvc plots diff $PREVIOUS_REF workspace \
            --show-vega --targets evaluation/plots/confusion_matrix.json > vega.json
          vl2svg vega.json confusion.svg

          dvc_report=$(dvc exp diff $PREVIOUS_REF --show-md)

          cat <<EOF > report.md
          # CML Report
          ## Plots
          ![Precision & Recall](./prc.svg)
          ![Confusion Matrix](./confusion.svg)

          ## Metrics and Params
          ### ${PREVIOUS_REF} → workspace
          ${dvc_report}
          EOF

          if test ${{ github.event_name }} = pull_request; then
            cml comment update --pr report.md
          else
            cml comment create report.md
          fi
